dataset-archive-list:
  inputPath: s3://S3_BUCKET/dwca-imports

dwca-avro:
  inputPath: /data/biocache-load/{datasetId}
  tempLocation: /data/biocache-load/{datasetId}

collectory:
  wsUrl: https://collections-test.ala.org.au/ws/
  httpHeaders:
    Authorization: ALA_API_KEY

alaNameMatch:
  wsUrl: https://namematching-ws.test.ala.org.au/

uuid:
  throwErrorOnValidationFail: false

sds:
  wsUrl: https://sensitive-ws.test.ala.org.au/

imageService:
  wsUrl: https://images-test.ala.org.au/
  timeoutSec: 300
  httpHeaders:
    apiKey: ALA_API_KEY

speciesListService:
  wsUrl: https://lists.ala.org.au/

samplingService:
  wsUrl: https://sampling.ala.org.au/sampling-service/

solr:
  zkHost: ZK_URL

elastic:
  esHosts: ES_HOSTS
  esAlias: ES_ALIAS
  indexNumberShards: 6
